import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navber from "../components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/imagehover.css/2.0.0/css/imagehover.min.css"
				/>
			</head>
			<body className={inter.className}>
				<header className="sticky top-0 z-50">
					<Navber />
				</header>
				<main className="relative">{children}</main>
				<footer className="mt-20">
					<Footer />
				</footer>
			</body>
		</html>
	);
}
